### PR TITLE
email-validator added

### PR DESCRIPTION
**Pull request by ayush3160**
issue #30 . Email validator function added.

### CODE REVIEW

**Review by suryapratapsinghsuryavanshi — CHANGES_REQUESTED** [review]
@ayush3160, I reviewed your code, and find the method only checks the "\__@\__.__" formats are not closely fit any valid email. Can you refine this method? And do not forget about exporting method in the index.js file.

**Comment by ayush3160** [comment]
@suryapratapsinghsuryavanshi , I have fixed the export in index.js. Can you let me know if this method can work :-

 let emailValidator = (email) => {

    let emailformat = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;

    if(email.match(emailformat)){
        return true
    }else{
        return false
    }
}

Or if you can give any example where it is failing.

**Comment by suryapratapsinghsuryavanshi** [comment]
@ayush3160 

Please push the new fixed code, I can't able to see your new commit.

**Comment by ayush3160** [comment]
@suryapratapsinghsuryavanshi, I have pushed the code please have a look.

**Review by suryapratapsinghsuryavanshi — APPROVED** [review]
Great @ayush3160, please continue your further contribution.

**Pull request merged**
